export const CHANGE_RECOMMEND_LIST = 'recommend/RECOMMEND_LIST';
export const CHANGE_RECOMMEND_NEW_SONG = 'recommend/RECOMMEND_NEW_SONG'
export const CHANGE_ENTER_LOADING = 'recommend/CHANGE_ENTER_LOADING';