export const SET_HOT_KEYWORDS = "search/SET_HOT_KEYWORDS"
export const SET_SEARCH_SUGGEST_LIST = 'search/SEARCH_SUGGEST_LIST';
export const SET_SEARCH_RESULT_LIST = 'search/SEARCH_RESULT_LIST';
export const CHANGE_ENTER_LOADING = 'search/CHANGE_ENTER_LOADING';